#+title: SVM
#+Author: Puscas Raul Andrei
#+OPTIONS: ^:{}

* TABLE OF CONTENTS :toc:
- [[#the-learning-methodology][The learning methodology]]
  - [[#supervised-learning][Supervised Learning]]
  - [[#learning-and-generalisations][Learning and Generalisations]]
- [[#linear-learning-machines][Linear Learning Machines]]
  - [[#linear-classification][Linear Classification]]
  - [[#theorems-and-definitions][Theorems and Definitions]]
  - [[#fishers-discriminant][Fisher's discriminant]]
  - [[#multi-class-discrimination][Multi-class discrimination]]
  - [[#linear-regressions][Linear regressions]]
  - [[#leastsquares][Least–Squares]]
- [[#kernel-induced-feature-spaces][Kernel-Induced feature spaces]]
  - [[#learning-in-feature-space][Learning in Feature Space]]
  - [[#the-implicit-mapping-into-feature-space][The implicit Mapping into Feature Space]]
  - [[#making-kernels][Making kernels]]
  - [[#making-kernels-from-features][Making kernels from features]]
  - [[#working-in-feature-space][Working in feature space]]
- [[#generalisation-theory][Generalisation Theory]]
  - [[#probably-approximate-correct-learning-pac-model][Probably Approximate Correct Learning (PAC model)]]
  - [[#vapnik-chervonenkis-vc-theory][Vapnik Chervonenkis (VC) Theory]]
  - [[#the-vc-theory][The VC Theory]]
  - [[#theorem-43][Theorem 4.3]]
  - [[#margin-based-bounds][Margin-Based bounds]]
- [[#optimisation-theory][Optimisation Theory]]
  - [[#definition-51][Definition 5.1]]
  - [[#lagrangian-theory][Lagrangian theory]]
  - [[#theorem-55-fermat][Theorem 5.5 Fermat]]
  - [[#definition-57][Definition 5.7]]
- [[#support-vector-classification][Support vector classification]]
  - [[#the-maximal-margin-classifier][The maximal margin classifier.]]
  - [[#proposition-61][Proposition 6.1]]

* The learning methodology

** Supervised Learning
The approach of using examples to synthetise programs is knows as the learning methodology, and in the particular case when the examples are input/ output pairs it is known as supervised learning.
The input/ output pairings typically reflect a functional relationship mapping the input to outputs, though this is not always the case as for examples when the input is altered by noise. When an underlying function from inputs to outputs exists, it is called the /target function/.
There exists unsupervised training learning, where there are no output pairing existent in the training data.
There are also other methods of learning which consider more complex interactions between a learner and their environment.

Another type of variation is the way in which the training data is generated and how they are presented to the learner.
There is a distinction between *batch learning* in which all the data is given to the learner at once and *on-line* learning in which the learner receives on example at a time, and gives their estimate of the output, before receiving the correct value.

** Learning and Generalisations
The ability of a hypothesis to correctly classify data not in the training set is known as generalization. Shifting the goal to generaliazation removes the need to know the underlying form of the hypothesis.

* Linear Learning Machines

** Linear Classification
Binary classification is frequently performed by using a real-valued function
        f : X ⊆ Rⁿ –> R
In the following way:
The input x = (x₁, x₂, ..., xₙ) is assigned the positive class if f(x) ≥ 0, otherwise the negative class.
We consider the case where f(x) is linear so it can be written as:
        f(x) = ⟨ W • x ⟩ + b
        f(x) = Σᵢⁿ wᵢxᵢ + b
Where (w, b) ϵ (Rⁿ× R) are paramteres that control the function.

THE PERCEPTRON ALGORITHM
#+begin_example PSEUDOCODE
    w₀ <– 0, b₀ <– 0, k <– 0
    R <– max({xᵢ | 1 ≤ i ≤ l}) ## l - the size of the training set
    repeat
            for i = 1 to l
                    if yᵢ(⟨ wₖ, xᵢ ⟩ + bₖ) ≤ 0 then
                            wₖ₊₁ <– wₖ + μyᵢxᵢ
                            bₖ₊₁ <– bₖ + μyᵢR²
                            k <- k + 1
                    end if
            end for
    untill no mistakes are made inside the for loop
    return (wₖ, bₖ) where k is the number of mistakes
#+end_example

** Theorems and Definitions

*** Theorem 2.3 Novikoff
Let S be a non-trivial training set, and let
        R = max₁ˡ( ∥xᵤ∥ ), where ∥xᵤ∥ represents the *geometric norm*
        ∥xᵤ∥ = √(x₁² + x₂² + ... + xₙ²)
Suppose that there exists a vector ∥wₒₚₜ∥ = 1 and
        yᵢ(⟨wₒₚₜ × xᵢ⟩ + bₒₚₜ) ≥ y
Then the number of mistakes made by the perceptron is at most
        S = (2R/y)²

*** Definition 2.6
Fix a value γ > 0, we can define the margin slack variable of an example (xᵢ, yᵢ) with respect to the hyperplane (w, b) and target margin γ as:
        ξ((xᵢ, yᵢ) (w, b), γ) = ξᵢ = max(0,γ-γᵢ(⟨w × xᵢ⟩ + b))
Informally, this quantity measures how much a point failed to have a margin of γ from the hyperplane. if ξᵢ > γ then xᵢ is missclassified by (w, b).
The norm ∥ξ∥₂ measures the amount by which training fails to have margin γ.

*** Theorem 2.7 (Freud and Schapire)
Let S be a non-trivial training set with no duplicate examples. ∥xᵢ∥ ≤ R. Let (w, b) be any hyperplane with ∥w∥ = 1, let γ > 0.
        D = √Σᵢˡ ξ² = √Σᵢˡ ξ((xᵢ, yᵢ), (w, b), γ)²
Then the number of mistakes in the first execution of the for loop is:
        ((2 × R + D)/γ)²

*** Writing hypotheses in a dual-form
It is important to note that the perceptron algorithm works by adding misclassified positive training examples or subtracting misclassified negative to an initial arbitrarily chosen weight vector. Without loss of generality, we have assumed that the initial weight vector is the *0* vector, and so the final hypothesis will be:
        w = Σᵢᴸ αᵢγᵢxᵢ
Where since the sign of the coefficient xᵢ is given by the classification γᵢ, the αᵢ are positive values proportional to the number of times misclassification
of xᵢ has caused the weight to be updated.
Points that have caused fewer mistakes will have a smaller αᵢ, whereas difficult ones will have a larger value. αᵢ is often called the embedding strength.

Once sample S has been fixed, one can think of the α as alternative representation of the hypothesis in different/ dual coordinates.
The decision function can be written as
    h(x) = sgn(⟨w × x⟩ + b)
         = sgn(⟨Σ₁ᴸ αⱼγⱼxⱼ × x⟩ + b)
         = sgn(Σ₁ᴸ αⱼγⱼ⟨xⱼ × x⟩ + b)

#+begin_example PSEUDOCDE
    Given training set S
    α <- 0, b <- 0
    R <- max₁ᴸ ∥xᵢ∥
    repeat
            for i = 1 to L
                if γᵢ(Σ₁ᴸ αᵢγⱼ ⟨xⱼ × xᵢ⟩ ≤ 0) then
                        αᵢ <- αⱼ + 1
                        b <- b + γᵢ × R²
                end if
            end for
    untill no mistakes were made inside the for loop
    return (α, b) to define function h(x)
#+end_example

Compared to the standard perceptron, where we maintain a vector w that gets updated everytime we make a mistake as  w = γᵢ × xᵢ + w. Which for a staring 0 vector just accumulates to a linear combination of the inputs.
In the dual form, we no longer maintain the W, we maintain for each xᵢ how many times it was mistakenly calculated -> αᵢ.
So, when we make a new prediction we have:
       1. In the Classic Perceptron algorithm : ⟨ w * x ⟩ + b
       2. In the dual form:  ⟨Σ₁ᴸ αⱼxⱼγⱼ × x⟩ + b. We compute the weight vector on the fly.
Due to this dual form representation, we can easily swap the dot product with a Kernel-Function, or a different kind of function.

Remark 2.11 The Gram Matrix
The training data only enter the algorithm through the entries of the matrix
        G = (⟨xᵢ × xⱼ⟩)ˡᵢ,ⱼ₌₁

** Fisher's discriminant
The perceptron is guaranteed to converge only if the data are linearly separable. One procedure that does not suffer from this limitation is Fisher's discriminant, which is aimed at finding the hyperplane (w, b) on which the projection of the data is maximally separated.
The cost function to be optimised is the following:
        F = (m₁ - m₋₁)²/(σ₁² + σ²₋₁)
Where mᵢ and σᵢ are the mean and standard deviation of the function output values:
        {⟨w × xⱼ⟩ + b : γⱼ = i}

** Multi-class discrimination
The problem of binary discrimination can also be solved by defining a vector wᵢ and bias bᵢ for each class. Each time a new instance has to be classified, both functions are evaluated, and then point is x is assigned to the class 1 if ⟨w₁ × x⟩ + b₁ ≥ ⟨w₋₁ × x⟩ + b₋₁, to class -1 otherwise.

For a multi class classification problem, the output domain is Y = {1, 2, 3... n}, we associate a weight vector and a bias to each of the classes and
for point x it gets assigned to max₁ᴸ(⟨x × wᵢ⟩ + b)

** Linear regressions
The problem of linear regression consists in finding a linear function:
        f(x) = ⟨w × x⟩ + b
That bests interpolates a given set S of training points labeled from Y ⊆ R. Geometrically this corresponds to a hyperplane fitting the given points.

** Least–Squares
Given a training set S, with xᵢ ϵ X ⊆ Rⁿ, yᵢ ϵ R, the problem of linear regression is to find a linear function f that models the data.
The least-squared approach prescribes choosing (w, b) in order to minimise the sum of the squares deviations of the data
        L(w, b) = Σ₁ᴸ (yᵢ - ⟨w × xᵢ⟩ + b)²

* Kernel-Induced feature spaces
In this chapter, the kernel technique will be introduced, which provides one of the main building blocks of SVMs.

** Learning in Feature Space
The complexity of the target function that is to be learned depends on the way it is represented, and the difficulty of learning a task can vary accordingly. Ideally, a representation that matches the specific learning problem should be chosen. So one common strategy in machine learning is changing the representation of the data.
        x = (x₁, x₂, ..., xₙ) —> θ(x) = (θ₁(x), θ₂(x2), ..., θₙ(x))
This steps represents mapping the input space X into a feature specta F = {θ(x) | x ϵ X }

The fact that simply mapping the data into another space can greatly simplify the task has been known for a long time in ML, and has given rise to a number of techniques for selecting best representation of data. The quantities introduced to describe the data are usually caled features, while the original quantities are sometimes called attributes.

Different approaches to feature selection exists.
Frequently one seeks to identify the smallest number of features that still convey the essential information contained in the original attributes.
This is known as dimensionality reduction.
        x = (x₁, x₂, ..., xₙ) —> θ(x) = (θ₁(x), θ₂(x), ..., θₖ(x)), k < n

Feature selection should be viewed as part of of the learning process.
It is somewhat of an arbitrary step, which reflects our prior expectations of the underlying target function.

** The implicit Mapping into Feature Space
In order to learn non-linear relations with a linear machine, we need to select a set of non-linear features and to rewrite the data into a new representation. This is equivalent to applying a fixed non-linear mapping of the data to a feature space, in which the linear machine is used.
Hence, the set of hyptheses we consider will be functions of the type:

        f(x) —> Σᵢⁿwᵢθᵢ(x) + b , where θ : X –> F is a non-linear map from the input space to some feature space.

This means that we will build non-linear machines in 2 steps: first a non-linear mapping transforms the data into a feature space F, and then the linear machine is used to classify the feature space.
As shown in Chapter 2, one important property of linear learning machines is that they can be expressed in a dual representation. This means that the hypothesis can be expressed as a linear combination of the training sets, so that the decision rule can be evaluated simply as a dot product between the test points and train points.
        f(x) = Σᵢᴸ αᵢγᵢ⟨θ(xᵢ) × θ(x)⟩ + b
If we have a way of computing ⟨θ(xᵢ) × θ(x)⟩ in feature space directly as a function of the original input points, it becomes possible to merge the two steps (mapping into the feature space and computing the output) needed to build a non-linear learning machine. We call such a direct computation a *kernel function*.

*** Definition 3.4 Kernel Function
A kernel is a function K, such that for all x,z ϵ X
        K(x, z) = ⟨θ(x) × θ(z)⟩, where θ is a mapping from X to a feature space F
An important consequence of the dual representation is that the dimension of the feature space need not affect the computation. As one does not represent the feature vectors explicitly, the number of operations required to compute the inner product using the kernel function is not necessarily proportional to the dimension of the feature space.
The use of kernels makes it possibly to map the data implicitly into a feature space and to train a linear machine in such a space, potentially side-stepping the computational problems inherent in evaluating the feature map. The only information used about the training examples is their Gram Matrix in the feature space, also known as the kernel matrix and it will be denoted further by *K*.
The key to this approach is finding a kernel function that can be evaluated efficiently. Once we have such a function the decision rule can be evaluated by at most L evaluations of the kernel:
        f(x) Σ₁ᴸ αᵢγᵢK(xᵢ, x) + b
One of the curious facts about using a kernel, is that we do not need to know the underlying feature map in order to be able to learn in the feature space.
The idea of a kernel generalises the standard inner product in the input space. It is clear that this inner product provides an example of a kernel.
        K(x, z) = ⟨x × z⟩
We can also take the feature map to be any fixed linear transformation x -> Ax, for some matrix A
K(x, z) = ⟨Ax × Az⟩ = x'A'Az = x'Bz, where by construction B = A'A is a square symmmetric positive semi-definite matrix.

** Making kernels
The use of a kernel-function is an attractive computational short-cut. If we wish to use this approach, there appears to be a need to first create a complicated feature-space, then work out the kernel function.
In practice, the approach taken is to define a kernel function directly, hence implicitly defining the feature space. In this way, we avoid the feature space not only in the computation of the inner products, but also in the design of the learning machine itself.

Before we can design a kernel function, we need to know what properties a function K(x, z) are necessary for it to be a kernel of some feature space.

*** Kernel Characterisation
1. The function must be symmetric
   K(x, z) = ⟨θ(x) × θ(z)⟩ = ⟨θ(z), θ(x)⟩ = K(z, x)
2. Satisfy the inequalities that follow from the Cauchy-Schwarz inequity
   K(x, z)² = ⟨θ(x) × θ(z)⟩² ≤ ∥θ(x)∥² ∥θ(z)∥²
            = ⟨θ(x) × θ(z)⟩ ⟨θ(z) × θ(z)⟩ = K(x, x) K(z, z)
3. Mercer's Theorem
   Mercer's Theorem provides a characterisation of when a function K(x, z) is a kernel.
   Considering a finite space x = {x₁, x₂, ..., xₙ} and supposed K(x, z) is a symmetric function on X. Consider the matrix
        K = (K(xᵢxⱼ))ⁿᵢⱼ₌₁
        Kᵢⁿ= [K(xᵢ, x₁), K(xᵢ, x₂), ... K(xᵢ, xⱼ) ... ]

        K - symmetric => There exists an orthogonal matrix V such as K = V ∧ V', where ∧ is a diagonal matrix containing the eigenvalues αᵢ of K with corresponding eigenvectors vₜ = (υₜᵢ)₁ⁿ
        Assuming all the eigenvalues are non-negative

** Making kernels from features
Another way to obtain a kernel is of course to start from the features, and to obtain it by working out their inner product. In this case there is no need to check for positive semi-definiteness since this will follow automatically from the definition as an inner product. Let us consider a kernel over a a discrete space, in this case finite strings in order to illustrate the potential of the method for non-Euclidian spaces.

*** (String subsequence kernels)
Let Σ be a finite alphabet. A string is a finite sequence of characters from Σ, including the empty sequence. For strings s, t we denote the length of s by |s|. And by st the string concatenated by the addition of t to s. The string s[i:j] is the substring sᵢsᵢ₊₁...sⱼ. We say that u is a subsequence of s, if there exist indicies i=(i₁, ..., iᵤ) such that uⱼ = sᵢ. We denote by Σⁿ the set of all finite strings of length n, and by Σ^* the set of all strings.

We now define the feature space Fₙ = R^{Σ²}. The feature mapping θ for a string s is given by the defining the u coordinate θᵤ(s) for each s ϵ Σⁿ.

** Working in feature space
Since the embedding given by the feature mapping is non linear and hence in general defines a n dimensional sub-manifold of the feature space, linear combinations of images often do not correspond to images of any input point. Nevertheless, we are able to represent such points using the dual representation, and provided we are only concerned with distances and inner products the kernel can be used without computing an explicit feature vector.
Let θ(X) be the image of the input space under the feature mapping, and define F = co(θ(X)) to be the space of all finite linear combination of points from θ(X).

* Generalisation Theory
In this chapter the main results of VC theory are reviewed.

** Probably Approximate Correct Learning (PAC model)
The main assumption on which the model is based is that the data used in training and testing are generated independently and indentically (i.i.d) according to an unknown but fixed distribution D. We assume this is a distribution over input/ output parining (x, y) ϵ {-1, 1}, an approach which subsumes the case where the output y is determined by a fixed target function t of the input ( y = t(x) ). Adaptations of the model have considered the case where the distribution changes over time, or where there is not full independence in the generation of examples in the training set (augmenting data via linear transformations). The model also ignores the possibility that the learner might be able to influence which examples are chosen, an ingredient that is studied in the query model of learning.
        err_{d}(h) = D{ (x, y) : h(x) ≠ y}
Such a measure is also referred to as a risk functional, as its measure the expected error rate. The aim of the analysis will be to assert bounds on this error in terms of several quantities. Perhaps the most crucial is the number of training examples used. Frequentelly pac results have been presented as bounds on the number of training examples to achieve a certain error. This is also known as the sample complexity of the problem. We prefer bounding the error as the number of training examples required as this error can be directly used in chossing between classes.
Consider a fixed inference rule for selecting a hypothesis h_{s} from the class H of classification rules at the learners disposal.
        S = ((x₁, y₁), (x₂, y₂), ..., (xₗ, yₗ)), l - number of training examples chosen i.i.d according to D.
In this setting, we can view the generalisation error err_{DS}(h) as a random variable depending on the random selection of the training set. The statistical mechanical method approach for analyzing generalization aims to bound the expected generalisation error, where the expectation is taken over the random selection of the training sets of a particular size. There are situations when such an estimation can be unreliable, an example being is the estimator given by cross-validation. The pac model of learning requires a generalisation error bound that is unlikely to fail. It therefore bounds the tail of the distribution (least probable cases when picking l random examples from the training set S [ex: a dice giving 6 10 times in a row, compared to a normal-distribution of numbers]) of the generalisation error random variable err_{}_{D}(hₛ). The size of the tail is determined by a futher parameter δ specified by the learner. Hence, a pac bound has the form ϵ = (l, H, S) and asserts that with probability atleast 1 - δ over randomly generated sets S, the generalisation error of the selected hypothesis hₛ will be bound by:
        err_{D}(hₛ) ≤ ϵ(l, H, S)
or in other words it is probably approximately correct. This is equivalent to asserting that the probability that training set S gives rise to a hypothesis with a large error is small:
        D^{l}= { S : err_{D}(h_{S}) > ϵ(l, H, δ) } < δ *INEQUALITY 4.2*
The PAC approach has the flavour of a statistical test in the sense that it asserts the probability that the dataset has mislead us is small. This corresponds to saying that the result is significant at the δ level, or in other words that *the probability that a set has mislead us is at most δ*.

** Vapnik Chervonenkis (VC) Theory
For a finite set of hypothesis it is not hard to obtain a bound in the form of inequality. Assume we use the inference rule that selects any hypothesis h that is consistent with the training examples in S. The probability that all l examples are consistent with the hypothesis h for which err(h) ≥ ϵ, is bounded by:
        D^{l} = { S : h consistent and err(h) > ϵ} ≤ (1 - ϵ)ᴸ ≤ exp(-ϵl)
Considering that all hypotheses from H have a large error, the probability that one is consistent with S is:
        |H|exp(-ϵL)
By the union bound on the probability that one of the events occurs. This bounds the probability that a consistent hypotheses h_{S} has error greater than ϵ as given:
        D^{l}{S: h_{S} consistent and err(h_{S}) ≤ ϵ} ≤ |H|exp(-ϵl)
In order to ensure the right-hand side is less than δ we set
        ϵ = ϵ(l, H, S) = 1/l ln(|H|/δ) [SIMPLE BOUND]
*Explaining note*
        Here, truly ϵ measures the required accuracy of the model we are training (we want to achieve an accuracy of ϵ = 0.0001), but in order to do that we must ensure that we have a dataset S that covers all possible examples. Even if you have a great learning algorithm, there is always a tiny mathematical chance that the training data S you were given is completely unrepresentative of the real world.
        Imagine you are trying to learn if a coin is fair. You flip it 10 times, and by pure, astronomical fluke, it comes up "Heads" all 10 times. Your learner will conclude "This coin always results in heads."
        This bad dataset is determined by the δ parameter. Therefore a small δ, 1e-5, would force us in that case to use a huge dataset because of bound:
                ϵ = 1/l ln(|H|/δ), where ϵ is fixed, and preferably a small number (in the case of creating a learner). When testing it we compute it.
This simple bound already shows how the complexity of the function class H (architecture of all hypothesis H) measured here by its cardinality has a direct effect on the error bound. Clearly choosing H too large can cause to overfitting (using a Deep architecture on a dataset of 10 XOR examples ). The result also shows that a property relating the true error to the empirical error (ϵ - δ ) holds for all hypotheses of H. Learning theory relies on bounding the difference between empirical and true estimates of error uniformly over the set of hypotheses and conditions that can arise. As we have seen, this is not difficult when the number of hypotheses is finite, but VC theory generalised this to a number of infinite hypotheses.

We assume a inference rule that delivers any consistent hypotheses and denote by err_{S}(h) the number of errors made by hypotheses h on training set S. The key to bounding over an infinite set of functions (so deep-architectures, non-deep in order to avoid overfitting) is to bound the probability of inequality 4.2 by twice the probability of having zero error on the training examples but high error on a second random example S'
        D^{l}= { S : ∃ h ϵ H : err_{S}(h) = 0, err_{D}(h) > ϵ } ≤ 2D^{2l}= {SS' : ∃h ϵ H : err_{S}(h) = 0, err_{S'}> ϵl / 2}
The quantity on the right hand-side is bounded by *fixing* the 2l sample and counting different orders in which the points might have been chosen while still keeping all the errors in the second sample (they do not help in computing the weights????). Since each order of permutation is equally likely the fraction of orders that satisfy the property is an upper bound on its probability. By only considering permutations that swap corresponding points from the first and second sample, we can bound the fraction of such permutations by 2^{-ϵl/2} independently of the particular set of 2l points
The advantage of considering errors over a finite 2l sample space, is that the hypotheses space becomes finite, since there can be no more than 2^{2l} classifications.
In order to obtain a union bound on the overall probability of the right hand side all that is required is a bound on the size of the hypotheses space when restricted to 2l, a quantity known as the growth function:
        B_{H}(l) = max_{x₁, ..., xₗ}|{h(x₁), h(x₂), ..., h(x_{l}): h ϵ H}
The first observation about this quantity is that it can not exceed 2ˡ, since the set over which the maximum is sought are all subsets of 2l.
A set of points {x₁, ..., xₗ} for which the set
        {h(x₁), h(x₂), ..., h(x_{l})} = {-1, 1}^{l}
Is said to be shattered by H. If there are sets of any size which can be shattered by H then the growth function is equal to 2^{l} for all l.
The final ingredient of VC theory is the analysis of the case when there is a d which is the largest set size that can be shattered by H. In this case the growth function can be bounded as follows:
        B_{H}(l) ≤ (el/d)^{d}
The value d is knows as the VC dimension of H

*Explanation note*
Here, we generalize the theory so that we may use the PAC model of learning to compute the error even on deep–architectures( training on deep networks, infinite hypotheses) and be able to tell if the model did overfit or not by comparing to another sample of the dataset during training. So since we have a 2l training examples, split into two halves, both taken from the same set generated by the distribution D, it is highly likely that the learned model performs in the same way on both of them, showing similar errors. If we overfit the training set, it will fail this test.
*Compared to a test set*, this proves that all of the hypotheses of H will perform in a similar way for the same l. Using a test set with prove that a certain h \epsilon H performs a certain way, but using this we prove that all of H does.

** The VC Theory
Let H be a hypothesis space of VC dimension d. For any probability distribution D on X x {-1, 1} with probability 1 - δ over l random examples S, on any hypothesis h from H that is consistent with S has error no more than:
        err(h) ≤ ϵ(l, H, δ) ≤ 2/l (d × log(2el/d) + log(2/δ))

** Theorem 4.3
Let H be a hypothesis space of VC dimension atleast d ≥ 1. Then for any learning algorithm there exists distributions such that with probability atleast 1 - δ over l training examples the error of hypothesos h returned is:
        max(d-1/32, 1/l x ln(1/l))
 The theorem states that for a hypothesis class H with a high VC dimension there exist input probabilities that the learner requires a high amount og training data in order to generalize.
 We can therefore see that that finite VC dimension characterises learnability in the pac sense - we can bound the error as a function of the VC dim in a distribution-free way, but for infinite VC dimensions it is impossible to do so.

 In order to apply the theory to linear learning machines, we must compute the VCdim(L) of a linear funcion class L ∈ Rⁿin terms of dimension n, that is to determine the largest number d of examples that can be classified in all 2ᵈ possible ways by different linear functions.
 *Proposition*
 1. Given any set S consisting of n + 1 training examples there exists a function l ∈ L that consistenly classifies S irrespective of the labelling given to the training points.
    2. For any set l > n + 1 there is atleast one classification that can not be realised by any l ∈ L

** Margin-Based bounds
*** Maximal margin-bounds
When proving Vc theory we reduced the infinite space of H to the finite set of functions that can be realised over 2l training examples. A large margin γ can reduce the effective size of the function space even further because the generalisation performance can be approximated by a function whose output is within γ/2 of the double points in the sample.
The estimation of the size of such a class requires some extra machinery.

*Definition 4.8*
Let F be a class of real-valued functions on a domain X. A \gamma–cover of F with respect to a sequence of inputs x=(x₁, x₂, x₃.., xₙ) is a finite set of functions B that for any f ∈ F there exists a g ∈ B such that max_{1≤i≤l}(|f(xᵢ) - g(xᵢ)) < \gamma. The size of the smallest such cover is denoted by N(F, S, γ) while the covering numbers of F are the values N(F, l, γ) = max_{S∈Xˡ}N(F, S, \gamma)
We can now show that the VC theory for a hypothesis f with margin m_{S}(f) = γ on the training set S can be reformulated in terms of the covering numbers of the underlying real-valued function class.
        Dˡ = { S:\exists f ∈ F : err_{S}(f)=0, m_{S}(f) ≥ γ, err_{D}(f) > ϵ } ≤ 2D^{2l} { SS^ : \exists f ∈ F : err_{S}(f)=0, m_{S}(f) ≥ γ, err_{S^}(f) > ϵl/2  }
Where considering that there is a fixed, threshold err_{S} represents the number of errors that f made on the thresholded output.
Taking a γ/2 cover of F with respect to the sequence SS^ it follows that err_{S}(g) = 0 and ms(g) > γ/2, while if f made an error on some point x than g must have a margin less than γ/2 of x.

*** Theorem 4.9
Consider thresholding a real-valued function class F and fix γ ∈ R⁺. For any probability distribution D on X x { -1, 1 } with probability 1 - δ over l training examples any hypothesis f ∈ F that has margin m_{S}(f) ≥ \gamma on S has error no more than:
        err_{S}(f) ≤ ϵ(l, F, γ, δ) = 2/l(log N(F, 2l, γ/2) + log(2/δ))

*** Remark 4.10
The theorem shows how generalisation can be bounded on the \gamma values that has been observerd during training. We expect that for larger values of γ the size of log to get smaller. This quantity can be observed as an effective VC dimension and so we can expect that by setting a large margin will result in a good generalisation from a small dataset.

*** Definition 4.12
Let F be a class of real-valued functions defined on a domain X. We say a set of points {x₁, x₂, x₃, ...., xₙ} is γ-shattered by F, if there exist real numbers rᵢ, i = 1...n such that for every binary classification b ∈ {-1, 1} there exists f_{B} ∈ F
                | ≥ rᵢ + \gammaᵢ if bᵢ = 1
        f_{B}(xᵢ) = |
                | ≤ rᵢ + gammaᵢ if bᵢ = -1 |

This dimension is also referred as scale-sensitive VC dimension. The real numbers rᵢ can be viewed as individual thresholds for each point while γ-shattering implies that we can realise every classification with margin γ relative to the chosen thresholds.
Clearly the larger the γ value the smaller the set that can be shattered since the restrictions placed on the functions that can be used become stricter.
If the rᵢ is required to be the same for all values of X, then this dimension is known as fat shattering.

By imposing this marginal maximal bound we are efficiently reducing the hypothesis space that a learning model may produce to a very narrow number by choosing a high \gamma. That is why we can work in very high dimensional spaces with SVMs and have a relatively small dataset. By adding this extra number, we are effictively reducing the space even narrower than the VC dimension which crumbles under infinite or very high dimensional hypothesis classes.
That is the main difference between a neural network and SVM, although both are linear classifiers. The ANN is only bounded by its VC dimension, and not bounded further by the maximal margin bound, that is why for ANN operating in the same dimension as an SVM we may require a way bigger dataset in order to be capable to generalize.

***  Theorem 4.16
Suppose that X is the ball of radius R in an inner product space H. X = { x ∈ H :  x _{H} ≤ 1, x ∈ X} and consider the class of functions
        L = { x <-> ⟨w × x\rangle : \parallel x  _{H} ≤ 1 }
Then
        fat_{L}(γ) ≤ (R/γ)²
*** Theorem 4.18
Consider thresholding real-valued functions L with unit weight vectors on an inner product X fix γ ∈ R⁺. For any probability distribution D on X x {-1, 1} with support in a ball of radius R around the origin with probability 1 - δ over l training examples any hypothesis f ∈ L that has margin m_{S}(f) ≥ γ on S has error no more than:
        err_{D}(f) ≤ ϵ(l, L, δ, γ) = 2/l(64R²/\gamma2 × log(elγ/4R) × log(128lR²/γ²) + log(4/δ))

* Optimisation Theory
The general form of the problem is that of finding the minimum or maximum subject to some constraints. The general optimisation problem can be stated as follows:
** Definition 5.1
Given primal functions f, gᵢ, i = 1...k and hᵢ i = 1...m defined on a domain Ω ∈ Rⁿ
        minimise f(w)
        subject to gᵢ(w) ≤ 0
                   hᵢ(w) = 0
Where f(w) is called the objective function and g and h are called the inequality and equality constraints.
Since maximisation problems can be converted to minimisation problems by swapping the sign of f(w), the choice of minimisation does not represent a constraint. Similarly, any constraints can be rewritten in the above form.
The region of the domain where the objective function is defined and where all the constraints are met is called the feasible region and we will denote it by:
        R = { r ∈ Ω : g(r) ≤ 0 && h(r) = 0 }
A solution of the optimisation problem is a point w* ∈ R such that there exists no other point w ∈ R for which f(w) < f(w*). Such point is known as a global minimum.

An objective function where the inequality and equality constraints are all linear functions is called a linear programme. If the objective function is quadratic while the constraints are all linear, the optimisation problem becomes a quadratic problem.
An inequality constraint is said to be active if the solution w* satisfies g(w*) = 0. An inequality constraint is considered to be active if the solution w* satisfies g(w) = 0 otherwise it is said to be inactive. Slack variables can also be introduced and they are denoted by ξ.

*Definition 5.3*
A real-valued function is considered convex if there exists w ∈ Rⁿif ∀ w,u ∈ Rⁿ and for any θ ∈ (0,1)
        f(θw + (1-θ)u) ≤ θf(w) + (1-θ)f(u)
        If a strict inequality holds it is called a strict convex function.
If a function f is convex, then for any local minimum w* of the unconstrained optimisation problem, it is also a global minimum since for any u ≠ w* there exists a θ close enough to 1 such that

*Definition 5.4*
An optimisation problem for which the set Ω the objective function and all the constraints are convex is said to be convex.

** Lagrangian theory
** Theorem 5.5 Fermat
A necessary condition for w* to be a minimum of f(w*) f ∈ C¹ is ∂f(w*)/∂w = 0. This condition together with convexity of f is sufficient.

** Definition 5.7
Given an optimisation problem with objective function f(w) and equality constraints hᵢ(w) = 0, i = 1,2, ..., m we define the lagrangian function as
        L(w, β) = f(w) + Σᵢᵐ βhᵢ(w) where the coefficients βᵢ are called the lagrange multipliers.

* Support vector classification
The aim is to devise a computationally efficient way of learning good separating hyperplanes, and by good we mean we will understand ones that optimise the bounds described in the generalisation chapter.
The generalisation theory provides clear ways about how to control capacity and hence prevent overfitting by controlling the hyperplanes margin measures.
Different generalisation bounds exist, motivating different algoritmhs: one can for example optimise the maximal margin bound, the margin distribution, the number of support vectors.
This chapter will introduce the most common approach which is to optimise the norm of the weight vector.

** The maximal margin classifier.
The simplest model of SVM is the maximal margin classifier which is also the first to get introduced and the simplest one. It works only for data that is linearly separable in the feature space and hence can not be used in many real-world situations.
Theorem 4.18 bounds the generalisation of the learning model by the m_{S}(f) of the learning function f. The dimensionality of the space in which the function operates is not taken into consideration. The optimal margin classifier optimizes this bound by separating the data with the maximal margin hyperplane, and given that the bound is not dependent on the function space, the separation can be sought in any kernel-induced feature space.
The strategy is implemented by reducing it to a convex optimisation problem: minimising a quadratic function under linear inequality constraints.
In the definition of linear classifiers there is an inherent degree of freedom due to the fact that the associated hyperplane (w, b) does not change if we rescale to the hyperplane(α \times w, \alpha × b) for any positive \alpha ∈ Rⁿ. There will be however a difference between the functional margin and the geometric one. Theorem 4.18 involves the geometric margin that is the functional margin of a normalised vector. Hence we can equally well optimise the geometric margin by fixing the functional margin to be 1 (creating canonical hyperplanes) and minimising the norm of the vector.

If w is the weight vector realising a functional margin of 1 on the positive point x⁺ and the negative point x⁻ we can compute the geometric margin as follows:
A functional margin of 1 represents that:
        ⟨w × x⁺ + b\rangle = 1
        ⟨w × x⁻ + b\rangle = -1
While to compute the geometric margin we must normalise w. The geometric margin γ is then the functional margin of the resulting classifier
        γ = 1/2 (⟨w/∥w∥₂ × x+\rangle ⟨w/∥w∥₂ × x-\rangle) -
        γ = 1/ (2 * ∥w∥₂) × (⟨w × x+\rangle ⟨w × x-⟩)
        γ = 1/∥w∥₂
Hence the geometric margin is equal to 1/∥w∥₂.
** Proposition 6.1
Given a linearly separable training example
        S = (x₁, x₂, ..., xₙ) × {-1, 1}
        The hyperplane (w, b) that solves the problem realises the maximal margin hyperplane with geometric margin γ = 1 / ∥w∥₂
