#+title: SVM
#+Author: Puscas Raul Andrei
#+OPTIONS: ^:{}

* TABLE OF CONTENTS :toc:
- [[#the-learning-methodology][The learning methodology]]
  - [[#supervised-learning][Supervised Learning]]
  - [[#learning-and-generalisations][Learning and Generalisations]]
- [[#linear-learning-machines][Linear Learning Machines]]
  - [[#linear-classification][Linear Classification]]
  - [[#theorems-and-definitions][Theorems and Definitions]]
  - [[#fishers-discriminant][Fisher's discriminant]]
  - [[#multi-class-discrimination][Multi-class discrimination]]
  - [[#linear-regressions][Linear regressions]]
  - [[#leastsquares][LeastвҖ“Squares]]
- [[#kernel-induced-feature-spaces][Kernel-Induced feature spaces]]
  - [[#learning-in-feature-space][Learning in Feature Space]]
  - [[#the-implicit-mapping-into-feature-space][The implicit Mapping into Feature Space]]
  - [[#making-kernels][Making kernels]]
  - [[#making-kernels-from-features][Making kernels from features]]
  - [[#working-in-feature-space][Working in feature space]]
- [[#generalisation-theory][Generalisation Theory]]
  - [[#probably-approximate-correct-learning][Probably Approximate Correct Learning]]
  - [[#vapnik-chervonenkis-vc-theory][Vapnik Chervonenkis (VC) Theory]]

* The learning methodology

** Supervised Learning
The approach of using examples to synthetise programs is knows as the learning methodology, and in the particular case when the examples are input/ output pairs it is known as supervised learning.
The input/ output pairings typically reflect a functional relationship mapping the input to outputs, though this is not always the case as for examples when the input is altered by noise. When an underlying function from inputs to outputs exists, it is called the /target function/.
There exists unsupervised training learning, where there are no output pairing existent in the training data.
There are also other methods of learning which consider more complex interactions between a learner and their environment.

Another type of variation is the way in which the training data is generated and how they are presented to the learner.
There is a distinction between *batch learning* in which all the data is given to the learner at once and *on-line* learning in which the learner receives on example at a time, and gives their estimate of the output, before receiving the correct value.

** Learning and Generalisations
The ability of a hypothesis to correctly classify data not in the training set is known as generalization. Shifting the goal to generaliazation removes the need to know the underlying form of the hypothesis.

* Linear Learning Machines

** Linear Classification
Binary classification is frequently performed by using a real-valued function
        f : X вҠҶ RвҒҝ вҖ“> R
In the following way:
The input x = (xвӮҒ, xвӮӮ, ..., xвӮҷ) is assigned the positive class if f(x) вүҘ 0, otherwise the negative class.
We consider the case where f(x) is linear so it can be written as:
        f(x) = вҹЁ W вҖў x вҹ© + b
        f(x) = ОЈбөўвҒҝ wбөўxбөў + b
Where (w, b) Пө (RвҒҝГ— R) are paramteres that control the function.

THE PERCEPTRON ALGORITHM
#+begin_example PSEUDOCODE
    wвӮҖ <вҖ“ 0, bвӮҖ <вҖ“ 0, k <вҖ“ 0
    R <вҖ“ max({xбөў | 1 вүӨ i вүӨ l}) ## l - the size of the training set
    repeat
            for i = 1 to l
                    if yбөў(вҹЁ wвӮ–, xбөў вҹ© + bвӮ–) вүӨ 0 then
                            wвӮ–вӮҠвӮҒ <вҖ“ wвӮ– + Ојyбөўxбөў
                            bвӮ–вӮҠвӮҒ <вҖ“ bвӮ– + ОјyбөўRВІ
                            k <- k + 1
                    end if
            end for
    untill no mistakes are made inside the for loop
    return (wвӮ–, bвӮ–) where k is the number of mistakes
#+end_example

** Theorems and Definitions

*** Theorem 2.3 Novikoff
Let S be a non-trivial training set, and let
        R = maxвӮҒЛЎ( вҲҘxбөӨвҲҘ ), where вҲҘxбөӨвҲҘ represents the *geometric norm*
        вҲҘxбөӨвҲҘ = вҲҡ(xвӮҒВІ + xвӮӮВІ + ... + xвӮҷВІ)
Suppose that there exists a vector вҲҘwвӮ’вӮҡвӮңвҲҘ = 1 and
        yбөў(вҹЁwвӮ’вӮҡвӮң Г— xбөўвҹ© + bвӮ’вӮҡвӮң) вүҘ y
Then the number of mistakes made by the perceptron is at most
        S = (2R/y)ВІ

*** Definition 2.6
Fix a value Оі > 0, we can define the margin slack variable of an example (xбөў, yбөў) with respect to the hyperplane (w, b) and target margin Оі as:
        Оҫ((xбөў, yбөў) (w, b), Оі) = Оҫбөў = max(0,Оі-Оібөў(вҹЁw Г— xбөўвҹ© + b))
Informally, this quantity measures how much a point failed to have a margin of Оі from the hyperplane. if Оҫбөў > Оі then xбөў is missclassified by (w, b).
The norm вҲҘОҫвҲҘвӮӮ measures the amount by which training fails to have margin Оі.

*** Theorem 2.7 (Freud and Schapire)
Let S be a non-trivial training set with no duplicate examples. вҲҘxбөўвҲҘ вүӨ R. Let (w, b) be any hyperplane with вҲҘwвҲҘ = 1, let Оі > 0.
        D = вҲҡОЈбөўЛЎ ОҫВІ = вҲҡОЈбөўЛЎ Оҫ((xбөў, yбөў), (w, b), Оі)ВІ
Then the number of mistakes in the first execution of the for loop is:
        ((2 Г— R + D)/Оі)ВІ

*** Writing hypotheses in a dual-form
It is important to note that the perceptron algorithm works by adding misclassified positive training examples or subtracting misclassified negative to an initial arbitrarily chosen weight vector. Without loss of generality, we have assumed that the initial weight vector is the *0* vector, and so the final hypothesis will be:
        w = ОЈбөўбҙё ОұбөўОібөўxбөў
Where since the sign of the coefficient xбөў is given by the classification Оібөў, the Оұбөў are positive values proportional to the number of times misclassification
of xбөў has caused the weight to be updated.
Points that have caused fewer mistakes will have a smaller Оұбөў, whereas difficult ones will have a larger value. Оұбөў is often called the embedding strength.

Once sample S has been fixed, one can think of the Оұ as alternative representation of the hypothesis in different/ dual coordinates.
The decision function can be written as
    h(x) = sgn(вҹЁw Г— xвҹ© + b)
         = sgn(вҹЁОЈвӮҒбҙё ОұвұјОівұјxвұј Г— xвҹ© + b)
         = sgn(ОЈвӮҒбҙё ОұвұјОівұјвҹЁxвұј Г— xвҹ© + b)

#+begin_example PSEUDOCDE
    Given training set S
    Оұ <- 0, b <- 0
    R <- maxвӮҒбҙё вҲҘxбөўвҲҘ
    repeat
            for i = 1 to L
                if Оібөў(ОЈвӮҒбҙё ОұбөўОівұј вҹЁxвұј Г— xбөўвҹ© вүӨ 0) then
                        Оұбөў <- Оұвұј + 1
                        b <- b + Оібөў Г— RВІ
                end if
            end for
    untill no mistakes were made inside the for loop
    return (Оұ, b) to define function h(x)
#+end_example

Compared to the standard perceptron, where we maintain a vector w that gets updated everytime we make a mistake as  w = Оібөў Г— xбөў + w. Which for a staring 0 vector just accumulates to a linear combination of the inputs.
In the dual form, we no longer maintain the W, we maintain for each xбөў how many times it was mistakenly calculated -> Оұбөў.
So, when we make a new prediction we have:
       1. In the Classic Perceptron algorithm : вҹЁ w * x вҹ© + b
       2. In the dual form:  вҹЁОЈвӮҒбҙё ОұвұјxвұјОівұј Г— xвҹ© + b. We compute the weight vector on the fly.
Due to this dual form representation, we can easily swap the dot product with a Kernel-Function, or a different kind of function.

Remark 2.11 The Gram Matrix
The training data only enter the algorithm through the entries of the matrix
        G = (вҹЁxбөў Г— xвұјвҹ©)ЛЎбөў,вұјвӮҢвӮҒ

** Fisher's discriminant
The perceptron is guaranteed to converge only if the data are linearly separable. One procedure that does not suffer from this limitation is Fisher's discriminant, which is aimed at finding the hyperplane (w, b) on which the projection of the data is maximally separated.
The cost function to be optimised is the following:
        F = (mвӮҒ - mвӮӢвӮҒ)ВІ/(ПғвӮҒВІ + ПғВІвӮӢвӮҒ)
Where mбөў and Пғбөў are the mean and standard deviation of the function output values:
        {вҹЁw Г— xвұјвҹ© + b : Оівұј = i}

** Multi-class discrimination
The problem of binary discrimination can also be solved by defining a vector wбөў and bias bбөў for each class. Each time a new instance has to be classified, both functions are evaluated, and then point is x is assigned to the class 1 if вҹЁwвӮҒ Г— xвҹ© + bвӮҒ вүҘ вҹЁwвӮӢвӮҒ Г— xвҹ© + bвӮӢвӮҒ, to class -1 otherwise.

For a multi class classification problem, the output domain is Y = {1, 2, 3... n}, we associate a weight vector and a bias to each of the classes and
for point x it gets assigned to maxвӮҒбҙё(вҹЁx Г— wбөўвҹ© + b)

** Linear regressions
The problem of linear regression consists in finding a linear function:
        f(x) = вҹЁw Г— xвҹ© + b
That bests interpolates a given set S of training points labeled from Y вҠҶ R. Geometrically this corresponds to a hyperplane fitting the given points.

** LeastвҖ“Squares
Given a training set S, with xбөў Пө X вҠҶ RвҒҝ, yбөў Пө R, the problem of linear regression is to find a linear function f that models the data.
The least-squared approach prescribes choosing (w, b) in order to minimise the sum of the squares deviations of the data
        L(w, b) = ОЈвӮҒбҙё (yбөў - вҹЁw Г— xбөўвҹ© + b)ВІ

* Kernel-Induced feature spaces
In this chapter, the kernel technique will be introduced, which provides one of the main building blocks of SVMs.

** Learning in Feature Space
The complexity of the target function that is to be learned depends on the way it is represented, and the difficulty of learning a task can vary accordingly. Ideally, a representation that matches the specific learning problem should be chosen. So one common strategy in machine learning is changing the representation of the data.
        x = (xвӮҒ, xвӮӮ, ..., xвӮҷ) вҖ”> Оё(x) = (ОёвӮҒ(x), ОёвӮӮ(x2), ..., ОёвӮҷ(x))
This steps represents mapping the input space X into a feature specta F = {Оё(x) | x Пө X }

The fact that simply mapping the data into another space can greatly simplify the task has been known for a long time in ML, and has given rise to a number of techniques for selecting best representation of data. The quantities introduced to describe the data are usually caled features, while the original quantities are sometimes called attributes.

Different approaches to feature selection exists.
Frequently one seeks to identify the smallest number of features that still convey the essential information contained in the original attributes.
This is known as dimensionality reduction.
        x = (xвӮҒ, xвӮӮ, ..., xвӮҷ) вҖ”> Оё(x) = (ОёвӮҒ(x), ОёвӮӮ(x), ..., ОёвӮ–(x)), k < n

Feature selection should be viewed as part of of the learning process.
It is somewhat of an arbitrary step, which reflects our prior expectations of the underlying target function.

** The implicit Mapping into Feature Space
In order to learn non-linear relations with a linear machine, we need to select a set of non-linear features and to rewrite the data into a new representation. This is equivalent to applying a fixed non-linear mapping of the data to a feature space, in which the linear machine is used.
Hence, the set of hyptheses we consider will be functions of the type:

        f(x) вҖ”> ОЈбөўвҒҝwбөўОёбөў(x) + b , where Оё : X вҖ“> F is a non-linear map from the input space to some feature space.

This means that we will build non-linear machines in 2 steps: first a non-linear mapping transforms the data into a feature space F, and then the linear machine is used to classify the feature space.
As shown in Chapter 2, one important property of linear learning machines is that they can be expressed in a dual representation. This means that the hypothesis can be expressed as a linear combination of the training sets, so that the decision rule can be evaluated simply as a dot product between the test points and train points.
        f(x) = ОЈбөўбҙё ОұбөўОібөўвҹЁОё(xбөў) Г— Оё(x)вҹ© + b
If we have a way of computing вҹЁОё(xбөў) Г— Оё(x)вҹ© in feature space directly as a function of the original input points, it becomes possible to merge the two steps (mapping into the feature space and computing the output) needed to build a non-linear learning machine. We call such a direct computation a *kernel function*.

*** Definition 3.4 Kernel Function
A kernel is a function K, such that for all x,z Пө X
        K(x, z) = вҹЁОё(x) Г— Оё(z)вҹ©, where Оё is a mapping from X to a feature space F
An important consequence of the dual representation is that the dimension of the feature space need not affect the computation. As one does not represent the feature vectors explicitly, the number of operations required to compute the inner product using the kernel function is not necessarily proportional to the dimension of the feature space.
The use of kernels makes it possibly to map the data implicitly into a feature space and to train a linear machine in such a space, potentially side-stepping the computational problems inherent in evaluating the feature map. The only information used about the training examples is their Gram Matrix in the feature space, also known as the kernel matrix and it will be denoted further by *K*.
The key to this approach is finding a kernel function that can be evaluated efficiently. Once we have such a function the decision rule can be evaluated by at most L evaluations of the kernel:
        f(x) ОЈвӮҒбҙё ОұбөўОібөўK(xбөў, x) + b
One of the curious facts about using a kernel, is that we do not need to know the underlying feature map in order to be able to learn in the feature space.
The idea of a kernel generalises the standard inner product in the input space. It is clear that this inner product provides an example of a kernel.
        K(x, z) = вҹЁx Г— zвҹ©
We can also take the feature map to be any fixed linear transformation x -> Ax, for some matrix A
K(x, z) = вҹЁAx Г— Azвҹ© = x'A'Az = x'Bz, where by construction B = A'A is a square symmmetric positive semi-definite matrix.

** Making kernels
The use of a kernel-function is an attractive computational short-cut. If we wish to use this approach, there appears to be a need to first create a complicated feature-space, then work out the kernel function.
In practice, the approach taken is to define a kernel function directly, hence implicitly defining the feature space. In this way, we avoid the feature space not only in the computation of the inner products, but also in the design of the learning machine itself.

Before we can design a kernel function, we need to know what properties a function K(x, z) are necessary for it to be a kernel of some feature space.

*** Kernel Characterisation
1. The function must be symmetric
   K(x, z) = вҹЁОё(x) Г— Оё(z)вҹ© = вҹЁОё(z), Оё(x)вҹ© = K(z, x)
2. Satisfy the inequalities that follow from the Cauchy-Schwarz inequity
   K(x, z)ВІ = вҹЁОё(x) Г— Оё(z)вҹ©ВІ вүӨ вҲҘОё(x)вҲҘВІ вҲҘОё(z)вҲҘВІ
            = вҹЁОё(x) Г— Оё(z)вҹ© вҹЁОё(z) Г— Оё(z)вҹ© = K(x, x) K(z, z)
3. Mercer's Theorem
   Mercer's Theorem provides a characterisation of when a function K(x, z) is a kernel.
   Considering a finite space x = {xвӮҒ, xвӮӮ, ..., xвӮҷ} and supposed K(x, z) is a symmetric function on X. Consider the matrix
        K = (K(xбөўxвұј))вҒҝбөўвұјвӮҢвӮҒ
        KбөўвҒҝ= [K(xбөў, xвӮҒ), K(xбөў, xвӮӮ), ... K(xбөў, xвұј) ... ]

        K - symmetric => There exists an orthogonal matrix V such as K = V вҲ§ V', where вҲ§ is a diagonal matrix containing the eigenvalues Оұбөў of K with corresponding eigenvectors vвӮң = (П…вӮңбөў)вӮҒвҒҝ
        Assuming all the eigenvalues are non-negative

** Making kernels from features
Another way to obtain a kernel is of course to start from the features, and to obtain it by working out their inner product. In this case there is no need to check for positive semi-definiteness since this will follow automatically from the definition as an inner product. Let us consider a kernel over a a discrete space, in this case finite strings in order to illustrate the potential of the method for non-Euclidian spaces.

*** (String subsequence kernels)
Let ОЈ be a finite alphabet. A string is a finite sequence of characters from ОЈ, including the empty sequence. For strings s, t we denote the length of s by |s|. And by st the string concatenated by the addition of t to s. The string s[i:j] is the substring sбөўsбөўвӮҠвӮҒ...sвұј. We say that u is a subsequence of s, if there exist indicies i=(iвӮҒ, ..., iбөӨ) such that uвұј = sбөў. We denote by ОЈвҒҝ the set of all finite strings of length n, and by ОЈ^* the set of all strings.

We now define the feature space FвӮҷ = R^{ОЈВІ}. The feature mapping Оё for a string s is given by the defining the u coordinate ОёбөӨ(s) for each s Пө ОЈвҒҝ.

** Working in feature space
Since the embedding given by the feature mapping is non linear and hence in general defines a n dimensional sub-manifold of the feature space, linear combinations of images often do not correspond to images of any input point. Nevertheless, we are able to represent such points using the dual representation, and provided we are only concerned with distances and inner products the kernel can be used without computing an explicit feature vector.
Let Оё(X) be the image of the input space under the feature mapping, and define F = co(Оё(X)) to be the space of all finite linear combination of points from Оё(X).

* Generalisation Theory
In this chapter the main results of VC theory are reviewed.

** Probably Approximate Correct Learning
The main assumption on which the model is based is that the data used in training and testing are generated independently and indentically (i.i.d) according to an unknown but fixed distribution D. We assume this is a distribution over input/ output parining (x, y) Пө {-1, 1}, an approach which subsumes the case where the output y is determined by a fixed target function t of the input ( y = t(x) ). Adaptations of the model have considered the case where the distribution changes over time, or where there is not full independence in the generation of examples in the training set (augmenting data via linear transformations). The model also ignores the possibility that the learner might be able to influence which examples are chosen, an ingredient that is studied in the query model of learning.
        err_{d}(h) = D{ (x, y) : h(x) вү  y}
Such a measure is also referred to as a risk functional, as its measure the expected error rate. The aim of the analysis will be to assert bounds on this error in terms of several quantities. Perhaps the most crucial is the number of training examples used. Frequentelly pac results have been presented as bounds on the number of training examples to achieve a certain error. This is also known as the sample complexity of the problem. We prefer bounding the error as the number of training examples required as this error can be directly used in chossing between classes.
Consider a fixed inference rule for selecting a hypothesis h_{s} from the class H of classification rules at the learners disposal.
        S = ((xвӮҒ, yвӮҒ), (xвӮӮ, yвӮӮ), ..., (xвӮ—, yвӮ—)), l - number of training examples chosen i.i.d according to D.
In this setting, we can view the generalisation error err_{DS}(h) as a random variable depending on the random selection of the training set. The statistical mechanical method approach for analyzing generalization aims to bound the expected generalisation error, where the expectation is taken over the random selection of the training sets of a particular size. There are situations when such an estimation can be unreliable, an example being is the estimator given by cross-validation. The pac model of learning requires a generalisation error bound that is unlikely to fail. It therefore bounds the tail of the distribution of the generalisation of the generalisation error random variable err_{}_{D}(hвӮӣ). The size of the tail is determined by a futher parameter Оҙ specified by the learner. Hence, a pac bound has the form Пө = (l, H, S) and asserts that with probability atleast 1 - Оҙ over randomly generated sets S, the generalisation error of the selected hypothesis hвӮӣ will be bound by:
        err_{D}(hвӮӣ) вүӨ Пө(l, H, S)

** Vapnik Chervonenkis (VC) Theory
For a finite set of hypothesis it is not hard to obtain a bound in the form of inequality. Assume we use the inference rule that selects any hypothesis h that is consistent with the training examples in S. The probability that all l examples are consistent with the hypothesis h for which err(h) вүҘ Пө, is bounded by:
        Dбҙё = { S : h consistent and err(h) > Пө} вүӨ (1 - Пө)бҙё вүӨ exp(-ПөL)
